### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by youmoqi** [zjukg/NATIVE#1]
I would like to ask you how long you train an epoch?

**Comment by Zhang-Each** [comment]
> I would like to ask you how long you train an epoch?

One epoch need ~60s on our machine.

**Comment by Zhang-Each** [comment]
> I would like to ask you how long you train an epoch?

1 epoch requires about 10s in our environments.

**Comment by youmoqi** [comment]
Thank you very much for your reply.
