### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by youmoqi** [zjukg/NATIVE#2]
! [1725625766675] (https://github.com/user-attachments/assets/22ea659b-d3ff-4bd6-8571-140cc846d030)
Dear Author,

First of all, thank you so much for sharing this project. I ran into some issues during my deployment (see attached image) that didn't run smoothly. Have you ever encountered a similar problem? If it's convenient, can you confirm if it's the code or configuration reason? Hope to get your help and guidance, thank you again for your contribution!

Best wishes!

**Comment by Zhang-Each** [comment]
Sorry but we haven't had this kind of problem before.

**Comment by Zhang-Each** [comment]
It seems that you should debug line by line.

**Comment by youmoqi** [comment]
! [1726108948012] (https://github.com/user-attachments/assets/5ad4de73-5200-43dd-ae8e-9a3e33e792f9)

Thank you very much for your answer. I am running with my own machine is reporting [OSError: [WinError 193] %1 is not a valid Win32 application] error, I would like to ask you are running with a 32-bit machine? Thank you.

**Comment by youmoqi** [comment]
I'm really sorry to delay you.

**Comment by Zhang-Each** [comment]
I run the code on the linux Ubuntu server.

**Comment by youmoqi** [comment]
I'm going back to get the server for a run, and I really appreciate you taking the time to answer my questions, thank you！
