### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by wzl0422** [zjukg/NATIVE#3]
尊敬的作者您好！我在运行Kuai16K数据集时，如下图：
![image](https://github.com/user-attachments/assets/2a0d3b62-ce88-4da0-a917-ab7819bed63e)
我想知道该数据集每个epoch大概多久？
我等了一段时间后台显示还是在读数据集，迟迟没有开始轮次，这是什么问题？望答复！感谢！

**Comment by wzl0422** [comment]
就是我发现只有Kuai16K这个数据集有问题，他没有产生对应的检查点，然后我发现它每跑完一次打印最终结果后又从epoch0从头开始跑第二遍了，怀疑是跟没有产生检查点有关，你们有同样的问题吗？或者说该如何解决呢？

**Comment by Zhang-Each** [comment]
你好，请提供更详细一点的说明，我们没有碰到过类似的情况。
