### ISSUE TITLE
模型部分

### ISSUE THREAD

**Issue by wzl0422** [zjukg/NATIVE#4]
尊敬的作者您好，我想问下关于您提出的模型部分在代码目录文件中是哪几个文件名的文件呢？还有strategy下的文件具体是什么作用的？分别有什么区别呢？望答复！非常感谢！！

**Comment by Zhang-Each** [comment]
你好，模型部分应该是AdvRelRotatEDB15K和AdvRelRotatEKuai16K，AdvRelRotatE这几个，strategy下面是负采样部分代码的实现，用于训练模型。

**Comment by wzl0422** [comment]
> 你好，模型部分应该是AdvRelRotatEDB15K和AdvRelRotatEKuai16K，AdvRelRotatE这几个，strategy下面是负采样部分代码的实现，用于训练模型。

好的好的 明白了 十分感谢回复！祝顺利！
