### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by wzl0422** [zjukg/NATIVE#5]
尊敬的作者您好！想请教一下关于论文中ReDAF模块中权重以及关系温度参数的设置在代码中的哪一个文件中？望回复！感激不尽！

**Comment by Zhang-Each** [comment]
你好，应该在mmkgc/module/model/AdvRelRotatE.py

**Comment by wzl0422** [comment]
> 你好，应该在mmkgc/module/model/AdvRelRotatE.py

好的！感谢！
