### ISSUE TITLE
模态占比

### ISSUE THREAD

**Issue by wzl0422** [zjukg/NATIVE#6]
第一个模块进行模态融合。请问作者，结构嵌入占比是非常大的吗？其余几种特征模态是不是占比非常小？我发现特征模态占比很小，几乎都是由结构模态占主导？我理解的有问题吗，想问一下原因。感谢！

**Comment by wzl0422** [comment]
另外我想请问，代码中多次提到的es，这个结构嵌入，它的维度在哪一块查看？我并没有看到他的传递

**Comment by Zhang-Each** [comment]
你好，是的。结构嵌入维度在模型的__init__中就是定义好的。

**Comment by wzl0422** [comment]
好的，其次我想请问一下作者模型关于判别器相关定义设置的代码文件是哪一个？我看adv下的modules.py都是生成器相关的

**Comment by Zhang-Each** [comment]
在mmkgc/adv/modules.py
