### ISSUE TITLE
代码无法运行，环境这里该如何配置呢？

### ISSUE THREAD

**Issue by lljoy123** [zjukg/NATIVE#7]
作者您好，我在ubuntu服务器中运行代码，但是出现的结果如图所示：
<img width="455" alt="Snipaste_2024-12-12_19-47-29" src="https://github.com/user-attachments/assets/cdb83505-9a89-4e5d-9cf6-013f788bc783" />
而且生成的txt中什么也没有
<img width="375" alt="Snipaste_2024-12-12_19-48-30" src="https://github.com/user-attachments/assets/f23942b5-5c6f-418b-a213-833ade3f7369" />
我想知道这是为什么呢？包括其他数据集也都是这种情况，我想知道是和我的cuda版本有关吗？我的cuda版本是10.2是否过低以至于不支持了呢？还是有什么别的问题呢？期待您的解答，不胜感激

**Comment by Zhang-Each** [comment]
你好，我没遇到过类似情况，建议逐行运行debug一下，应该不是环境配置的问题

**Comment by lljoy123** [comment]
谢谢您，我现在已经成功运行起来了

**Comment by zhangyushinibabadebaba** [comment]
你好，你的这个问题我也遇见了，你是怎么解决的呀？非常感谢期待你的回复

**Comment by lljoy123** [comment]
你好，我后来发现环境还是没问题的，这个项目1.7的torch版本都能跑起来，最后就是把里面的相对路径变成自己的服务器的绝对路径就好了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2025年07月05日 16:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [zjukg/NATIVE] 代码无法运行，环境这里该如何配置呢？ (Issue #7) |
zhangyushinibabadebaba left a comment (zjukg/NATIVE#7)

你好，你的这个问题我也遇见了，你是怎么解决的呀？非常感谢期待你的回复

**Comment by lljoy123** [comment]
说错了，是相对路径变成自己服务器的绝对路径就好了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2025年07月05日 16:09 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [zjukg/NATIVE] 代码无法运行，环境这里该如何配置呢？ (Issue #7) |
zhangyushinibabadebaba left a comment (zjukg/NATIVE#7)

你好，你的这个问题我也遇见了，你是怎么解决的呀？非常感谢期待你的回复

**Comment by zhangyushinibabadebaba** [comment]
你好。你说的变绝对路径我没听懂，是在代码哪里操作？感谢您的回复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: lljoy123 ***@***.***&gt;
发送时间: 2025年7月5日 16:36
收件人: zjukg/NATIVE ***@***.***&gt;
抄送: zhangyushinibabadebaba ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [zjukg/NATIVE] 代码无法运行，环境这里该如何配置呢？ (Issue #7)



lljoy123 left a comment (zjukg/NATIVE#7)
 说错了，是相对路径变成自己服务器的绝对路径就好了
 
 
 
 ---- 回复的原邮件 ----
 | 发件人 | ***@***.***&gt; |
 | 日期 | 2025年07月05日 16:09 |
 | 收件人 | ***@***.***&gt; |
 | 抄送至 | ***@***.***&gt;、State ***@***.***&gt; |
 | 主题 | Re: [zjukg/NATIVE] 代码无法运行，环境这里该如何配置呢？ (Issue #7) |
 zhangyushinibabadebaba left a comment (zjukg/NATIVE#7)
 
 你好，你的这个问题我也遇见了，你是怎么解决的呀？非常感谢期待你的回复
